exclude: 'node_modules|.git'
default_stages: [commit]
fail_fast: false

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
        files: 'cloud_storage.*'
        exclude: '.*json$|.*txt$|.*csv|.*md|.*svg'
      - id: check-yaml
      - id: no-commit-to-branch
        args: ['--branch', 'develop']
      - id: check-merge-conflict
      - id: check-ast
      - id: check-json
      - id: check-toml
      - id: check-yaml
      - id: debug-statements

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.2
    hooks:
      - id: pyupgrade
        args: ['--py310-plus']

  - repo: https://github.com/frappe/black
    rev: 951ccf4d5bb0d692b457a5ebc4215d755618eb68
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.7.1
    hooks:
      - id: prettier
        types_or: [javascript, vue, scss]
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
            .*node_modules.*|
            cloud_storage/public/dist/.*|
            cloud_storage/public/js/lib/.*|
            cloud_storage/templates/includes/.*
          )$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.44.0
    hooks:
      - id: eslint
        types_or: [javascript]
        args: ['--quiet']
        # Ignore any files that might contain jinja / bundles
        exclude: |
          (?x)^(
              .*node_modules.*|
              cloud_storage/public/dist/.*|
              cloud_storage/public/js/lib/.*|
              cloud_storage/templates/includes/.*
          )$

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        additional_dependencies: ['flake8-bugbear']

  - repo: https://github.com/codespell-project/codespell
    rev: v2.3.0
    hooks:
      - id: codespell
        additional_dependencies:
          - tomli

  - repo: https://github.com/agritheory/test_utils
    rev: v0.16.0
    hooks:
      - id: update_pre_commit_config
      - id: validate_copyright
        files: '\.(js|ts|py|md)$'
        args: ["--app", "cloud_storage"]
      - id: clean_customized_doctypes
        args: ["--app", "cloud_storage"]
      - id: validate_customizations
      - id: validate_python_dependencies
      - id: validate_javascript_dependencies

ci:
  autoupdate_schedule: weekly
  skip: []
  submodules: false
